[package]
name = 'danikvitek/mavka-did'
version = '0.3.3'
description = 'Парсер для формату Дід'
license = 'MIT'
readme = 'README.md'
repository = 'https://github.com/DanikVitek/mavka-did'

# See more keys and definitions at https://docs.wasmer.io/ecosystem/wapm/manifest

[dependencies]

[[module]]
name = 'mavka-did'
source = 'target\wasm32-wasmer-wasi\release\mavka_did.wasm'
abi = 'wasi'

[[command]]
name = 'mavka-did'
module = 'mavka-did'